#ifndef FENNEC_TEXTURE_H
#define FENNEC_TEXTURE_H

#include <GL/glew.h>
#include <GLFW/glfw3.h>

#include <stdlib.h>

#include "log.h"

/* NOTE:
 * If you want to disable texture generation logs, put this before you include
 * this file: #define FENNEC_NO_LOGS
 */

typedef struct {
    // the width of the texture
    int width;

    // the height of the texture
    int height;

    // the number of channels in the texture
    int channels;

    // the OpenGL ID that will be used when rendering the texture
    unsigned int id;
} FennecTexture;

/*
 * @description
 * Creates a new OpenGL texture from the file name provided. This can be bound
 * and then used by the program when drawing textured objects. The textures
 * generated by this library are always set to GL_NEAREST, so if you need
 * something else, you may need to consider writing your own implementation of
 * creating textures
 *
 * @argument
 * The filename to load
 *
 * @argument
 * The format of the texture, eg. RGB, RGBA
 */
FennecTexture *fennec_texture_new(char*, GLuint);

/*
 * @description
 * Creates an empty OpenGL texture with the width and height specified
 *
 * @argument
 * The width of the new texture
 *
 * @argument
 * The height of the new texture
 *
 * @argument
 * The format of the texture eg. GL_RGB, GL_RGBA, etc.
 */
FennecTexture *fennec_texture_empty(int, int, GLuint);

/*
 * @description
 * Frees the allocated FennecTexture, also deletes the texture within OpenGL
 */
void fennec_texture_free(FennecTexture*);

#endif
